Repository robotframework/RIDE, pull requests merged in 2020-07, with the labels that each got.

#2220 Bug fixing on perference panel
  src/robotide/context/__init__.py
  src/robotide/preferences/__init__.py
  src/robotide/preferences/widgets.py
Labels: enhancement

#2221 Fix dynamic doc
  src/robotide/lib/robot/running/dynamicmethods.py
  src/robotide/lib/robot/utils/__init__.py
  src/robotide/lib/robot/utils/robottypes.py
  src/robotide/lib/robot/utils/robottypes2.py
  src/robotide/lib/robot/utils/robottypes3.py
  src/robotide/spec/xmlreaders.py
Labels: enhancement, prio-high

#2230 Fix delete save txt
  src/robotide/editor/texteditor.py
  src/robotide/version.py
Labels: enhancement

#2223 Fixed issue#2108:
  src/robotide/namespace/resourcefactory.py
Labels: enhancement

#2216 Bugs fixing on editor grid
  src/robotide/editor/clipboard.py
  src/robotide/editor/kweditor.py
  src/robotide/publish/messages.py
  src/robotide/ui/actiontriggers.py
  src/robotide/ui/mainframe.py
Labels: enhancement

#2205 Update treenodehandlers.py to prevent freeze ups
  src/robotide/ui/treenodehandlers.py
Labels: enhancement

#2236 Fix cannot edit grid cell with wxPython 4.1.0
  src/robotide/editor/kweditor.py
Labels: ThirdParty, enhancement

#2232 Redesign RideEventHandler and file system monitoring feature
  src/robotide/application/application.py
  src/robotide/controller/project.py
  src/robotide/editor/kweditor.py
  src/robotide/editor/listeditor.py
  src/robotide/editor/settingeditors.py
  src/robotide/ui/mainframe.py
  src/robotide/ui/treeplugin.py
  src/robotide/utils/__init__.py
  src/robotide/utils/eventhandler.py
Labels: enhancement

#2237 Fix win10 system freeze when loading large project
  src/robotide/ui/treenodehandlers.py
  src/robotide/widgets/popupmenu.py
Labels: enhancement
